package com.ahmed.entities;
// Generated Feb 26, 2016 10:13:15 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CandidateInformation generated by hbm2java
 */
@Entity
@Table(name = "candidate_information", catalog = "final")
public class CandidateInformation implements java.io.Serializable {

	private Integer candidateId;
	private String district;
	private String image;
	private int age;
	private int maritalStatus;
	private String job;
	private String previous;
	private String qualification;
	private String degree;
	private String party;
	private String add;
	private int userId;

	public CandidateInformation() {
	}

	public CandidateInformation(String district, String image, int age, int maritalStatus, String job, String previous,
			String qualification, String degree, String party, String add, int userId) {
		this.district = district;
		this.image = image;
		this.age = age;
		this.maritalStatus = maritalStatus;
		this.job = job;
		this.previous = previous;
		this.qualification = qualification;
		this.degree = degree;
		this.party = party;
		this.add = add;
		this.userId = userId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "candidate_id", unique = true, nullable = false)
	public Integer getCandidateId() {
		return this.candidateId;
	}

	public void setCandidateId(Integer candidateId) {
		this.candidateId = candidateId;
	}

	@Column(name = "district", nullable = false)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "image", nullable = false)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "age", nullable = false)
	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@Column(name = "marital_status", nullable = false)
	public int getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(int maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	@Column(name = "job", nullable = false)
	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	@Column(name = "previous", nullable = false)
	public String getPrevious() {
		return this.previous;
	}

	public void setPrevious(String previous) {
		this.previous = previous;
	}

	@Column(name = "qualification", nullable = false)
	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

	@Column(name = "degree", nullable = false)
	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	@Column(name = "party", nullable = false)
	public String getParty() {
		return this.party;
	}

	public void setParty(String party) {
		this.party = party;
	}

	@Column(name = "add", nullable = false)
	public String getAdd() {
		return this.add;
	}

	public void setAdd(String add) {
		this.add = add;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

}
