package com.ahmed.entities;
// Generated Feb 26, 2016 10:13:15 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PendingRequest generated by hbm2java
 */
@Entity
@Table(name = "pending_request", catalog = "final")
public class PendingRequest implements java.io.Serializable {

	private Integer pendingId;
	private int userId;

	public PendingRequest() {
	}

	public PendingRequest(int userId) {
		this.userId = userId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pending_id", unique = true, nullable = false)
	public Integer getPendingId() {
		return this.pendingId;
	}

	public void setPendingId(Integer pendingId) {
		this.pendingId = pendingId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

}
