package com.ahmed.entities;
// Generated Feb 26, 2016 10:13:15 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person", catalog = "final")
public class Person implements java.io.Serializable {

	private Integer id;
	private String username;
	private String nationalId;
	private String password;
	private int type;
	private String fuzzy;

	public Person() {
	}

	public Person(String username, String nationalId, String password, int type, String fuzzy) {
		this.username = username;
		this.nationalId = nationalId;
		this.password = password;
		this.type = type;
		this.fuzzy = fuzzy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 55)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "national_id", nullable = false)
	public String getNationalId() {
		return this.nationalId;
	}

	public void setNationalId(String nationalId) {
		this.nationalId = nationalId;
	}

	@Column(name = "password", nullable = false, length = 55)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "fuzzy", nullable = false)
	public String getFuzzy() {
		return this.fuzzy;
	}

	public void setFuzzy(String fuzzy) {
		this.fuzzy = fuzzy;
	}

}
