package com.ahmed.entities;
// Generated Feb 26, 2016 10:13:15 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Votes generated by hbm2java
 */
@Entity
@Table(name = "votes", catalog = "final")
public class Votes implements java.io.Serializable {

	private Integer id;
	private int userId;
	private int candidateId;

	public Votes() {
	}

	public Votes(int userId, int candidateId) {
		this.userId = userId;
		this.candidateId = candidateId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "candidate_id", nullable = false)
	public int getCandidateId() {
		return this.candidateId;
	}

	public void setCandidateId(int candidateId) {
		this.candidateId = candidateId;
	}

}
