package com.ahmed.entities;
// Generated Feb 26, 2016 10:13:15 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Winners generated by hbm2java
 */
@Entity
@Table(name = "winners", catalog = "final")
public class Winners implements java.io.Serializable {

	private Integer id;
	private int personId;

	public Winners() {
	}

	public Winners(int personId) {
		this.personId = personId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "person_id", nullable = false)
	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

}
